bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: UfVz4OI38rAHfx6oxr8pX7VQUDpZ/onwURmFxlTlNCeI9Bfz2G+wqs3kwIva2dSJddLi106l8zxVp8I73yeteTHuUcuAwYclLzXV+x8JfCjtpaSL9BfhuUwrUgGP3Ij9vrgWwLjektuzKu1YOWjiv8TqKDYJPMM5gQYy8DVq2P9RNj0Ns+B0AZkOKSJrJSL6CCuxbXv4BErbM0vYKS2r8SHOzzsdr0jjQefTvi5zqUCsB1AHA1HCdcdPTtwt2PYMxdqZAdnPZUgZIwR3q68bQP68DQbpsjaGWz0LIOvtRvch9OBEUcd/ZzzifoGrpCjAHgb5hZvA+HzT49mg124ySm16ITCxGLX+GxoiDh79TjsXQZtPJDhGqU9WOFuGtk0qw31TYkGwniqyXWAmpT2oUBIhuSrBkxuQsSC2HDWNH5Pbf+IPwlET4JIroC5mWlBXF+kDp9xg/b0Oa8Ohd34GiMJEj8XOX0pCLkZPrkI2j0t2UyrBgMN/MgPHbBzjWiTnKZY2xvD/qZHpgVYARIBl2dVfrPRplCIFzlbaV3QoNi7YhK9kZz98hWsF34yDqVCERfA/j5+2xvzzEHzaY1N0ylP1cERj/XW1yr0aX847798a9EEHy7FMwNZJhZYywGNNKRwEbfqqYQgpPBlaR2W4B4azJDPhCeyeq6Ptia861IE=
conda_forge_output_validation: true
